### PR TITLE
add github actions to publish package to npm & gpr

### PR DESCRIPTION
**Pull request by o-az**
Action only runs when a tag is pushed && branch is `main`.

Action has 4 jobs:
- build and cache `dist` folder,
- grab cached `dist` and publish to npm registry,
- grab cached `dist` and publish to GitHub Package Registry,
- run https://github.com/antfu/changelogithub to generate GitHub release changelog.

So release process becomes `yarn release` which will trigger `release` script from `package.json` then prompt you to select new version (see example). Once version is selected, the version in `package.json` gets updated, git tags created and pushed. New tags being pushed will trigger CI.

CleanShot 2023-02-20 at 21 57 36

Also the above has to be done while in main otherwise CI won't run. So on code updates you would push those updates to whatever branch, merge to main, then run `yarn release`.

### CODE REVIEW

**Comment by o-az** [comment]
@tjayrush 

another thing is for org packages on npm and gpr, the package name tends to be `@org_name/<pkg_name>` so in TrueBlocks' case,  `@trueblocks/sdk` would be what I immediately think if if I wanted to install your sdk and didn't know the name. NPM allows orgs to have the `@org_name` prefix.

Example:
image

https://docs.npmjs.com/creating-and-publishing-an-organization-scoped-package

I haven't included this part in this PR but I can in another one.

**Comment by tjayrush** [comment]
> @tjayrush
> 
> another thing is for org packages on npm and gpr, the package name tends to be `@org_name/<pkg_name>` so in TrueBlocks' case, `@trueblocks/sdk` would be what I immediately think if if I wanted to install your sdk and didn't know the name. NPM allows orgs to have the `@org_name` prefix.
> 
> Example: image
> 
> https://docs.npmjs.com/creating-and-publishing-an-organization-scoped-package
> 
> I haven't included this part in this PR but I can in another one.

If I understand this properly, you're saying "most" packages would be called `trueblocks/sdk`, but this one isn't, but that it's easy to add.

If that's correct, let's go a head and make that change now.

If that's not correct, can you please further explain?

**Comment by o-az** [comment]
@tjayrush yup, your understanding is correct. So I will add the change to this repo.

**Comment by o-az** [comment]
@tjayrush done. Package renamed to `@trueblocks/sdk`. The `@org` piece is not optional  - it's reserved to org accounts so that's why it's used here.

**Comment by tjayrush** [comment]
I merged your first PR. Thanks for that. I think it caused a few conflicts. Can you please correct them? I'll merge this one when you do. Sorry if I did something wrong.

**Comment by tjayrush** [comment]
This is excellent. Thanks so much.

**Pull request merged**
